### PR TITLE
Hi, I updated the whole template plugin based on current text loader plugin implementation and underscore template plugin

### PR DESCRIPTION
**Pull request by eeroan**
Now it works with latest r.js and require.js versions both with node and java

### CODE REVIEW

**Comment by eeroan** [comment]
Here's a gentre reminder for accepting this pull requiest :). It works with latest require.js and r.js versions (2.1.2) and supports bundling with both node and rhino unlike the current one

**Comment by themouette** [comment]
I now use it and it works great
:+1:

**Comment by MarcoPolo** [comment]
I third the motion! lets merge this in!

**Comment by aglemann** [comment]
+1

**Comment by dawsontoth** [comment]
What's the advantage of embedding text.js and underscore's templating in tpl.js? Why not load them in as external dependencies, and tell people they need them too? That'd make PRs like this unnecessary.

For example: https://github.com/dawsontoth/requirejs-tpl/blob/master/tpl.js

**Comment by eeroan** [comment]
I totally aggree with you, but I couldn't make it work with the bundling. I tried to use the json loader plugin as an example until I discovered that I does not work either for bundles :(

If you find a way to make it work I'm more than hapy. I also remember that there where some problems when using relative paths for templates, like tpl!./template.html

Eero Anttila

Dawson Toth notifications@github.com kirjoitti 9.1.2013 kello 20.19:

**Comment by dawsontoth** [comment]
K! I'll look in to it. I bet I'll fail if you couldn't figure it out, but at least I'll have tons of fun in the process. ;)

**Comment by ingro** [comment]
+1!

**Comment by aglemann** [comment]
+1

**Comment by dawsontoth** [comment]
Fixed it. Now it works for me doing both: 1) dynamic inclusion, and 2) bundling. I also added some very verbose log output when attempting to compile invalid templates. https://github.com/dawsontoth/requirejs-tpl/blob/master/tpl.js Note that I set { variable: 'data' } as my default options in tpl.js (for performance of ease of falsy checking). If you want other settings, do it there.

Example bundled output (note that the text! is included too... not optimal, I know):

```
define('tpl!views/common/charts/templates/loader.html',[],function() { return function(data){
var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};
__p+='<div class="charts_container charts_container_'+
((__t=( data.type ))==null?'':_.escape(__t))+
'">\n</div>';
return __p;
} });
define('text!views/common/charts/templates/loader.html',[],function () { return '<div class="charts_container charts_container_<%- data.type %>">\n</div>';});
```

**Comment by eeroan** [comment]
Cool! It works. Great work! 

Could it be somehow possible to read the template settings from requirejs global settings? Do you have experience?
Then a minor thing: should the opening curly brace be on the same line instead of new line?

On 17.1.2013, at 23.40, Dawson Toth wrote:

> Fixed it. Now it works for me doing both: 1) dynamic inclusion, and 2) bundling. I also added some very verbose log output when attempting to compile invalid templates. https://github.com/dawsontoth/requirejs-tpl/blob/master/tpl.js Note that I set { variable: 'data' } as my default options in tpl.js (for performance of ease of falsy checking). If you want other settings, do it there.
> 
> Example bundled output (note that the text! is included too... not optimal, I know):
> 
> define('tpl!views/common/charts/templates/loader.html',[],function() { return function(data){
> var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};
> __p+='<div class="charts_container charts_container_'+
> ((__t=( data.type ))==null?'':_.escape(__t))+
> '">\n</div>';
> return __p;
> } });
> define('text!views/common/charts/templates/loader.html',[],function () { return '<div class="charts_container charts_container_<%- data.type %>">\n</div>';});
> —
> Reply to this email directly or view it on GitHub.

## 

Eero Anttila eero.anttila@iki.fi
+358 50 359 0079

**Comment by aglemann** [comment]
I wonder if you can use module config:
http://requirejs.org/docs/api.html#config-moduleconfig

So instead of:

var settings = { variable: 'data' };

You could do:

var settings = _.defaults(module.config() || {}, { variable: 'data' });

And in theory you could should be able to define the settings in Require's
config:

requirejs.config({
    config: {
        tpl: { interpolate : /{{(.+?)}}/g }
    }
});

Would need to test to make sure the whole thing works...

**Comment by dawsontoth** [comment]
Nice points, @eeroan and @aglemann. I've just pushed some changes. They work in my project great. I've also changed it back to use the default settings for better compatibility (and then you can override via the module config).

**Comment by eeroan** [comment]
Found something interesting: With this version where text plugin is included as dependency this is what happens for minified version:

``` javascript
define('text!app/navigation.html',[],function () { return '<header id="header" class="siteContent">\n  <h1 class="logo"><a href="#">Logo</a></h1>\n</header>\n';});

define('tpl!app/navigation.html',[],function() { return function(obj){
var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};
with(obj||{}){
__p+='<header id="header" class="siteContent">\n  <h1 class="logo"><a href="#">Logo</a></h1>\n</header>\n';
}
return __p;
} });
```

So each template is introduced twice: on version for text plugin and another for tpl.

**Comment by dawsontoth** [comment]
Fixed.

**Comment by nuragic** [comment]
Hi! Briefly... How the templateSettings can be overridden?

**Comment by eeroan** [comment]
By using module config (see above) with this fork: https://github.com/dawsontoth/requirejs-tpl/blob/master/tpl.js

**Pull request closed without merging**
